@startuml
autonumber
hide footbox
title User click in send button
box "App"
actor User as u
boundary Fragment as V <<View>>
control Presenter as P
entity Model as M
entity SocketIOInteractor as I
u -> V: click on send button
V -> P: onSend(Signal)
P -> M: sendMgs(Signal)
M -> I: sendMgs(String)
end box
I --> Server_Raspberry: SIGNAL
Server_Raspberry ->> AutomationPC: SIGNAL
Server_Raspberry <-- AutomationPC: ACK
I <- Server_Raspberry: ACK
M <- I: ACK
P <- M: ACK
V <- P: ACK
@enduml